apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: credit-fraud-inference
  namespace: monitoring
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: credit-fraud-inference
  namespaceSelector:
    matchNames:
      - ml-inference
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
