]633;E;{   echo "### MLFLOW: kubectl get all"\x3b   kubectl get all -n mlflow -o yaml\x3b    echo "\\n### MLFLOW: serviceaccounts"\x3b   kubectl get sa -n mlflow -o yaml\x3b    echo "\\n### MLFLOW: roles and rolebindings"\x3b   kubectl get role,rolebinding -n mlflow -o yaml\x3b    echo "\\n### MLFLOW: configmaps"\x3b   kubectl get configmap -n mlflow -o yaml\x3b    echo "\\n### MLFLOW: secrets"\x3b   kubectl get secret -n mlflow -o yaml\x3b    echo "\\n### MLFLOW: events"\x3b   kubectl get events -n mlflow --sort-by=.metadata.creationTimestamp\x3b } > $OUT_DIR/mlflow-full.yaml;6eabe6fa-72b9-494b-89de-19e3feeb3cf2]633;C### MLFLOW: kubectl get all
apiVersion: v1
items:
- apiVersion: v1
  kind: Pod
  metadata:
    creationTimestamp: "2025-12-13T21:13:15Z"
    generateName: mlflow-9cd8bf869-
    labels:
      app: mlflow
      pod-template-hash: 9cd8bf869
    name: mlflow-9cd8bf869-4fg4l
    namespace: mlflow
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: ReplicaSet
      name: mlflow-9cd8bf869
      uid: c4b44388-c8a3-4b77-b90a-e6d7c812d914
    resourceVersion: "362318"
    uid: ae1aa79f-cfc4-40a8-a874-d197675d96ee
  spec:
    containers:
    - command:
      - mlflow
      - server
      - --host=0.0.0.0
      - --port=5000
      env:
      - name: MLFLOW_BACKEND_STORE_URI
        value: postgresql://postgres:postgres@airflow-postgresql.airflow:5432/mlflow
      - name: MLFLOW_ARTIFACT_ROOT
        value: s3://bin2ml-mlflow-artifacts-eu-west-1/
      - name: AWS_STS_REGIONAL_ENDPOINTS
        value: regional
      - name: AWS_DEFAULT_REGION
        value: eu-west-1
      - name: AWS_REGION
        value: eu-west-1
      - name: AWS_ROLE_ARN
        value: arn:aws:iam::581212334853:role/mlflow-irsa
      - name: AWS_WEB_IDENTITY_TOKEN_FILE
        value: /var/run/secrets/eks.amazonaws.com/serviceaccount/token
      image: 581212334853.dkr.ecr.eu-west-1.amazonaws.com/yas-ml-inference:mlflow-postgres
      imagePullPolicy: IfNotPresent
      name: mlflow
      ports:
      - containerPort: 5000
        protocol: TCP
      resources: {}
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-csp6d
        readOnly: true
      - mountPath: /var/run/secrets/eks.amazonaws.com/serviceaccount
        name: aws-iam-token
        readOnly: true
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    nodeName: ip-10-0-1-15.eu-west-1.compute.internal
    preemptionPolicy: PreemptLowerPriority
    priority: 0
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: mlflow
    serviceAccountName: mlflow
    terminationGracePeriodSeconds: 30
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - name: aws-iam-token
      projected:
        defaultMode: 420
        sources:
        - serviceAccountToken:
            audience: sts.amazonaws.com
            expirationSeconds: 86400
            path: token
    - name: kube-api-access-csp6d
      projected:
        defaultMode: 420
        sources:
        - serviceAccountToken:
            expirationSeconds: 3607
            path: token
        - configMap:
            items:
            - key: ca.crt
              path: ca.crt
            name: kube-root-ca.crt
        - downwardAPI:
            items:
            - fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
              path: namespace
  status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: "2025-12-13T21:13:35Z"
      status: "True"
      type: PodReadyToStartContainers
    - lastProbeTime: null
      lastTransitionTime: "2025-12-13T21:13:15Z"
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2025-12-13T21:13:35Z"
      status: "True"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2025-12-13T21:13:35Z"
      status: "True"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2025-12-13T21:13:15Z"
      status: "True"
      type: PodScheduled
    containerStatuses:
    - containerID: containerd://ecfdf19d48a9493d331ff44631f508ced8da46d7e23dda1530ef5f0b9c3435c7
      image: 581212334853.dkr.ecr.eu-west-1.amazonaws.com/yas-ml-inference:mlflow-postgres
      imageID: 581212334853.dkr.ecr.eu-west-1.amazonaws.com/yas-ml-inference@sha256:d5ba689335cffe6c8cebd78a4dc80effa27072a5dfee5b9055cea09c4fecfe03
      lastState: {}
      name: mlflow
      ready: true
      restartCount: 0
      started: true
      state:
        running:
          startedAt: "2025-12-13T21:13:35Z"
    hostIP: 10.0.1.15
    hostIPs:
    - ip: 10.0.1.15
    phase: Running
    podIP: 10.0.1.195
    podIPs:
    - ip: 10.0.1.195
    qosClass: BestEffort
    startTime: "2025-12-13T21:13:15Z"
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"mlflow","namespace":"mlflow"},"spec":{"ports":[{"port":5000,"targetPort":5000}],"selector":{"app":"mlflow"}}}
    creationTimestamp: "2025-12-13T02:57:10Z"
    name: mlflow
    namespace: mlflow
    resourceVersion: "110275"
    uid: cb05b521-e2cc-4597-82ea-588ea0e4a607
  spec:
    clusterIP: 172.20.58.164
    clusterIPs:
    - 172.20.58.164
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - port: 5000
      protocol: TCP
      targetPort: 5000
    selector:
      app: mlflow
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"mlflow"},"name":"mlflow-metrics","namespace":"mlflow"},"spec":{"ports":[{"name":"metrics","port":5000,"targetPort":5000}],"selector":{"app":"mlflow"}}}
    creationTimestamp: "2025-12-15T03:07:06Z"
    labels:
      app: mlflow
    name: mlflow-metrics
    namespace: mlflow
    resourceVersion: "768641"
    uid: 62413925-8ccc-4936-a66a-1bfee19f4ee3
  spec:
    clusterIP: 172.20.218.243
    clusterIPs:
    - 172.20.218.243
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: metrics
      port: 5000
      protocol: TCP
      targetPort: 5000
    selector:
      app: mlflow
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "3"
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"mlflow","namespace":"mlflow"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"mlflow"}},"template":{"metadata":{"labels":{"app":"mlflow"}},"spec":{"containers":[{"command":["mlflow","server","--host=0.0.0.0","--port=5000"],"env":[{"name":"MLFLOW_BACKEND_STORE_URI","value":"postgresql://postgres:postgres@airflow-postgresql.airflow:5432/mlflow"},{"name":"MLFLOW_ARTIFACT_ROOT","value":"s3://bin2ml-mlflow-artifacts-eu-west-1/"}],"image":"581212334853.dkr.ecr.eu-west-1.amazonaws.com/yas-ml-inference:mlflow-postgres","imagePullPolicy":"IfNotPresent","name":"mlflow","ports":[{"containerPort":5000}]}],"serviceAccountName":"mlflow"}}}}
    creationTimestamp: "2025-12-13T02:56:44Z"
    generation: 3
    name: mlflow
    namespace: mlflow
    resourceVersion: "362322"
    uid: e063e7d3-abd6-4386-90a2-b8e2d689d680
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: mlflow
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: mlflow
      spec:
        containers:
        - command:
          - mlflow
          - server
          - --host=0.0.0.0
          - --port=5000
          env:
          - name: MLFLOW_BACKEND_STORE_URI
            value: postgresql://postgres:postgres@airflow-postgresql.airflow:5432/mlflow
          - name: MLFLOW_ARTIFACT_ROOT
            value: s3://bin2ml-mlflow-artifacts-eu-west-1/
          image: 581212334853.dkr.ecr.eu-west-1.amazonaws.com/yas-ml-inference:mlflow-postgres
          imagePullPolicy: IfNotPresent
          name: mlflow
          ports:
          - containerPort: 5000
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        serviceAccount: mlflow
        serviceAccountName: mlflow
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: "2025-12-13T02:56:45Z"
      lastUpdateTime: "2025-12-13T03:10:43Z"
      message: ReplicaSet "mlflow-9cd8bf869" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    - lastTransitionTime: "2025-12-13T21:13:36Z"
      lastUpdateTime: "2025-12-13T21:13:36Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    observedGeneration: 3
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1
- apiVersion: apps/v1
  kind: ReplicaSet
  metadata:
    annotations:
      deployment.kubernetes.io/desired-replicas: "1"
      deployment.kubernetes.io/max-replicas: "2"
      deployment.kubernetes.io/revision: "1"
    creationTimestamp: "2025-12-13T02:56:44Z"
    generation: 2
    labels:
      app: mlflow
      pod-template-hash: 6c86dcf4f9
    name: mlflow-6c86dcf4f9
    namespace: mlflow
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: Deployment
      name: mlflow
      uid: e063e7d3-abd6-4386-90a2-b8e2d689d680
    resourceVersion: "113062"
    uid: 5a818219-2a66-456a-858c-55743da6e614
  spec:
    replicas: 0
    selector:
      matchLabels:
        app: mlflow
        pod-template-hash: 6c86dcf4f9
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: mlflow
          pod-template-hash: 6c86dcf4f9
      spec:
        containers:
        - command:
          - mlflow
          - server
          - --host=0.0.0.0
          - --port=5000
          env:
          - name: MLFLOW_BACKEND_STORE_URI
            value: postgresql://postgres:postgres@airflow-postgresql.airflow:5432/postgres
          - name: MLFLOW_ARTIFACT_ROOT
            value: s3://bin2ml-mlflow-artifacts-eu-west-1/
          image: ghcr.io/mlflow/mlflow:v2.12.2
          imagePullPolicy: IfNotPresent
          name: mlflow
          ports:
          - containerPort: 5000
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        serviceAccount: mlflow
        serviceAccountName: mlflow
        terminationGracePeriodSeconds: 30
  status:
    observedGeneration: 2
    replicas: 0
- apiVersion: apps/v1
  kind: ReplicaSet
  metadata:
    annotations:
      deployment.kubernetes.io/desired-replicas: "1"
      deployment.kubernetes.io/max-replicas: "2"
      deployment.kubernetes.io/revision: "2"
    creationTimestamp: "2025-12-13T03:04:54Z"
    generation: 2
    labels:
      app: mlflow
      pod-template-hash: 74f8995cf9
    name: mlflow-74f8995cf9
    namespace: mlflow
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: Deployment
      name: mlflow
      uid: e063e7d3-abd6-4386-90a2-b8e2d689d680
    resourceVersion: "113820"
    uid: 180386c2-fe63-4a26-af55-68aa9a587a87
  spec:
    replicas: 0
    selector:
      matchLabels:
        app: mlflow
        pod-template-hash: 74f8995cf9
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: mlflow
          pod-template-hash: 74f8995cf9
      spec:
        containers:
        - command:
          - mlflow
          - server
          - --host=0.0.0.0
          - --port=5000
          env:
          - name: MLFLOW_BACKEND_STORE_URI
            value: postgresql://postgres:postgres@airflow-postgresql.airflow:5432/postgres
          - name: MLFLOW_ARTIFACT_ROOT
            value: s3://bin2ml-mlflow-artifacts-eu-west-1/
          image: 581212334853.dkr.ecr.eu-west-1.amazonaws.com/yas-ml-inference:mlflow-postgres
          imagePullPolicy: IfNotPresent
          name: mlflow
          ports:
          - containerPort: 5000
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        serviceAccount: mlflow
        serviceAccountName: mlflow
        terminationGracePeriodSeconds: 30
  status:
    observedGeneration: 2
    replicas: 0
- apiVersion: apps/v1
  kind: ReplicaSet
  metadata:
    annotations:
      deployment.kubernetes.io/desired-replicas: "1"
      deployment.kubernetes.io/max-replicas: "2"
      deployment.kubernetes.io/revision: "3"
    creationTimestamp: "2025-12-13T03:10:42Z"
    generation: 1
    labels:
      app: mlflow
      pod-template-hash: 9cd8bf869
    name: mlflow-9cd8bf869
    namespace: mlflow
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: Deployment
      name: mlflow
      uid: e063e7d3-abd6-4386-90a2-b8e2d689d680
    resourceVersion: "362321"
    uid: c4b44388-c8a3-4b77-b90a-e6d7c812d914
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: mlflow
        pod-template-hash: 9cd8bf869
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: mlflow
          pod-template-hash: 9cd8bf869
      spec:
        containers:
        - command:
          - mlflow
          - server
          - --host=0.0.0.0
          - --port=5000
          env:
          - name: MLFLOW_BACKEND_STORE_URI
            value: postgresql://postgres:postgres@airflow-postgresql.airflow:5432/mlflow
          - name: MLFLOW_ARTIFACT_ROOT
            value: s3://bin2ml-mlflow-artifacts-eu-west-1/
          image: 581212334853.dkr.ecr.eu-west-1.amazonaws.com/yas-ml-inference:mlflow-postgres
          imagePullPolicy: IfNotPresent
          name: mlflow
          ports:
          - containerPort: 5000
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        serviceAccount: mlflow
        serviceAccountName: mlflow
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 1
    fullyLabeledReplicas: 1
    observedGeneration: 1
    readyReplicas: 1
    replicas: 1
kind: List
metadata:
  resourceVersion: ""
\n### MLFLOW: serviceaccounts
apiVersion: v1
items:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-12-13T02:55:57Z"
    name: default
    namespace: mlflow
    resourceVersion: "109961"
    uid: 7ccfe755-da88-4846-bad8-887bdf761b51
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::581212334853:role/mlflow-irsa
    creationTimestamp: "2025-12-13T02:56:00Z"
    name: mlflow
    namespace: mlflow
    resourceVersion: "109982"
    uid: f0312283-8c82-494c-ab8f-b301b6b4adaa
kind: List
metadata:
  resourceVersion: ""
\n### MLFLOW: roles and rolebindings
apiVersion: v1
items: []
kind: List
metadata:
  resourceVersion: ""
\n### MLFLOW: configmaps
apiVersion: v1
items:
- apiVersion: v1
  data:
    ca.crt: |
      -----BEGIN CERTIFICATE-----
      MIIDBTCCAe2gAwIBAgIIMzb189Czfx0wDQYJKoZIhvcNAQELBQAwFTETMBEGA1UE
      AxMKa3ViZXJuZXRlczAeFw0yNTEyMTIxNzUyMjdaFw0zNTEyMTAxNzU3MjdaMBUx
      EzARBgNVBAMTCmt1YmVybmV0ZXMwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
      AoIBAQDmrfnjfyIgSekT7uGI6kgy/7CkfC4cCVqRKy1aauLTFBhkF+hQhfu3kBrv
      wo+bZdTMLougqhL18E1DfJyZSnhCu0C2ZplhIlejhoXgaATdJg8ZY2EcurERXNSN
      BmhIzmbHrJ4GF0tty48+Mp9yQDtBUCPYY6qSygOeG1sbDrtVWUyDeUja/f3kTax0
      uiZpa2cVVQBoIPCpOwKvaMQbCPomq9tugxlgbHSasfO+p6fjn0WvW4guEVR+A2l+
      r3VGOAL46yX31tOz2IRCioLgxSFvwmpod0bOPeMYzNRmsrSpnQPzJH4WXDnnXREQ
      wT5N5U8a+Dl5gb2haxGgJT6W9uCVAgMBAAGjWTBXMA4GA1UdDwEB/wQEAwICpDAP
      BgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBRebos98sU9n0hXRBdUEpcodFYsWTAV
      BgNVHREEDjAMggprdWJlcm5ldGVzMA0GCSqGSIb3DQEBCwUAA4IBAQAXsYBau1oM
      q0cjnQFLJzMprF4rSJgzPGru1LSVxGumvLAjcL1jb+PVrAAgp83dxR2bYN4nK64r
      rTLtV1TavsMEP9scXpgiZQxxk6YlAhf/ERo9H2lf/xgtLB0gwsFbgp5QaMIzjMnx
      x5LTdC33AsGQ78XUYaXJle5NXCySJzptp0illiU9DBPltmbds+FVLvDk/AbGBZB5
      fA3L/2gwGIsbuDuuwTXHjlhCq8r01ye1lBEtIq3ZhkORAGYQd5aUZk7ZcPguyw7E
      fXplK6wcjjszdbx5E9XaqL1qwOdt99WTYmPDZFV/YwaAB3OOuMXFzZMELDvnSWST
      D/V7+oOOx+jG
      -----END CERTIFICATE-----
  kind: ConfigMap
  metadata:
    annotations:
      kubernetes.io/description: Contains a CA bundle that can be used to verify the
        kube-apiserver when using internal endpoints such as the internal service
        IP or kubernetes.default.svc. No other usage is guaranteed across distributions
        of Kubernetes clusters.
    creationTimestamp: "2025-12-13T02:55:57Z"
    name: kube-root-ca.crt
    namespace: mlflow
    resourceVersion: "109960"
    uid: 03185b20-a877-4c36-8982-efdb379659da
kind: List
metadata:
  resourceVersion: ""
\n### MLFLOW: secrets
apiVersion: v1
items: []
kind: List
metadata:
  resourceVersion: ""
\n### MLFLOW: events
